global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'p10-backend'
    scrape_interval: 30s 
    metrics_path: '/p10-app/api/metrics'  
    static_configs:
      - targets: ['180.149.196.68']  
    scrape_timeout: 10s  
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'p10-app-traefik'
