{
 "title": "API Backend P10 - Monitoring",
 "tags": [
  "api",
  "backend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Taux de requêtes HTTP par seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[5m])",
     "legendFormat": "{{method}} {{route}} ({{status}})"
    }
   ]
  },
  {
   "title": "Total des requêtes HTTP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "p10_process_cpu_user_seconds_total",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Utilisation Mémoire",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "p10_process_resident_memory_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}